"""logboek

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 08:43:40.774548
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_success'), ['success'], unique=False)

    op.create_table('incoming_mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('attachments', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_mails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_mails_at'), ['at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming_mails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_mails_at'))

    op.drop_table('incoming_mails')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_success'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
